name: Push Ansible Release Tag

on:
  push:
    branches:
      - main
    paths:
      - deployments/ansible/galaxy.yml

permissions:
  contents: write

jobs:
  push-ansible-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Read current version of the Ansible Collection
        id: read-galaxy-yaml
        uses: cumulusds/get-yaml-paths-action@v0.1.0
        with:
          file: deployments/ansible/galaxy.yml
          version: version

      - name: Set new Ansible Release Tag
        run: git tag ansible-v${{ steps.read-galaxy-yaml.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tags
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true